export const icons = {
  profile: require('../icons/profile.png'),
  lock: require('../icons/lock.png'),
  eye: require('../icons/eye.png'),
  eye_hidden: require('../icons/eye-hidden.png'),
  chevron_left: require('../icons/chevron-left.png'),
  plus: require('../icons/plus.png'),
  food: require('../icons/food.png'),
  bike: require('../icons/bike.png'),
  bill: require('../icons/bill.png'),
  home_grey: require('../icons/home-grey.png'),
  rent: require('../icons/rent.png'),
  movie: require('../icons/movie.png'),
  shopping_bags: require('../icons/shopping-bags.png'),
  task: require('../icons/task.png'),
  activeHome: require('../icons/activeHome.png'),
  activeTask: require('../icons/task-glyph.png'),
  chvron_right: require('../icons/chevron-right.png'),
  edit: require('../icons/edit.png'),
  delete: require('../icons/delete.png'),
};
